sudo: required

language: java

services:
  - docker

after_success:
  - docker network create --driver bridge Group6
  - docker pull mongo
  - docker run -d --name mongo-dbserver --network se-methods mongo
  - docker build -t se_methods .
  - docker run --network se-methods Group6