@startuml

actor Users as "Users"
left to right direction
rectangle Database

rectangle "World Information" {
    usecase UC1 as "Display The list of Country by population from largest to smallest"
    Users - UC1
    UC1 - Database

    usecase UC2 as "Display the countries in Asia by population from largest to smallest"
    Users - UC2
    UC2 - Database

    usecase UC3 as "Display the countries in Southeast Asia by population from largest to smallest"
    Users - UC3
    UC3 - Database

    usecase UC4 as "Display Top 10 populated countries in the world"
    Users - UC4
    UC4 - Database

    usecase UC5 as "Display Top 10 populated countries in Asia"
    Users - UC5
    UC5 - Database

    usecase UC6 as "Display Top 10 populated countries in Southeast Asia"
    Users - UC6
    UC6 - Database

    usecase UC7 as "Display cities in the world organized by population from largest to smallest"
    Users - UC7
    UC7 - Database

    usecase UC8 as "Display the countries in Southeast Asia by population from largest to smallest"
    Users - UC8
    UC8 - Database

    usecase UC9 as "Display Top 10 populated cities in the world"
    Users - UC9
    UC9 - Database

    usecase UC10 as "Display Top 10 populated cities in the continent"
    Users - UC10
    UC10 - Database

    usecase UC11 as "Display Top 10 populated cities in a region"
    Users - UC11
    UC11 - Database

    usecase UC12 as "Display all cities in a region organized by population from largest to smallest"
    Users - UC12
    UC12 - Database

    usecase UC13 as "Display all cities in a country organized by population from largest to smallest"
    Users - UC13
    UC13 - Database

    usecase UC14 as "Display all cities in a district organized by population from largest to smallest"
    Users - UC14
    UC14 - Database

    usecase UC15 as "Display Top 10 populated cities in JAPAN"
    Users - UC15
    UC115 - Database

    usecase UC16 as "Display Top 10 populated cities in Chiba district"
    Users - UC16
    UC16 - Database

}

@enduml
