@startuml

actor Users as "Users"
left to right direction
rectangle Database

rectangle "World Information" {
    usecase UC1 as "Display The list of Country by population from largest to smallest"
    Users - UC1
    UC1 - Database

    usecase UC2 as "Display the countries in Asia by population from largest to smallest"
    Users - UC2
    UC2 - Database

    usecase UC3 as "Display the countries in Southeast Asia by population from largest to smallest"
    Users - UC3
    UC3 - Database

    usecase UC4 as "Display Top 10 populated countries in the world"
    Users - UC4
    UC4 - Database

    usecase UC5 as "Display Top 10 populated countries in Asia"
    Users - UC5
    UC5 - Database

    usecase UC6 as "Display Top 10 populated countries in Southeast Asia"
    Users - UC6
    UC6 - Database

    usecase UC7 as "Display cities in the world organized by population from largest to smallest"
    Users - UC7
    UC7 - Database

    usecase UC8 as "Display the countries in Southeast Asia by population from largest to smallest"
    Users - UC8
    UC8 - Database

     usecase UC9 as "Display Top 10 populated cities in the world"
     Users - UC9
     UC9 - Database

      usecase UC10 as "Display Top 10 populated cities in the continent"
      Users - UC10
      UC10 - Database

      usecase UC11 as "Display Top 10 populated cities in a region"
      Users - UC11
      UC11 - Database

      usecase UC12 as "Display all cities in a region organized by population from largest to smallest"
      Users - UC12
      UC12 - Database

      usecase UC13 as "Display all cities in a country organized by population from largest to smallest"
      Users - UC13
      UC13 - Database

      usecase UC14 as "Display all cities in a district organized by population from largest to smallest"
      Users - UC14
      UC14 - Database

      usecase UC15 as "Display Top 10 populated cities in JAPAN"
      Users - UC15
      UC15 - Database

      usecase UC16 as "Display Top 10 populated cities in Chiba district"
      Users - UC16
      UC16 - Database

      usecase UC17 as "Display the population of capital cities in the world from largest to smallest"
      Users - UC17
      UC17 - Database

      usecase UC18 as "Display Population of capital cities in Asia"
      Users - UC18
      UC18 - Database

      usecase UC19 as "Display Population of capital cities in Eastern Asia from largest to smallest"
      Users - UC19
      UC19 - Database

      usecase UC20 as "Display Top 10 populated capital cities in the world"
      Users - UC20
      UC20 - Database

      usecase UC21 as "Display Top 10 Populated capital cities in Asia continent"
      Users - UC21
      UC21 - Database

      usecase UC22 as "Display Top 10 Populated capital cities in Eastern Asia region"
      Users - UC22
      UC22 - Database

      usecase UC23 as "Display the population of people, people living in cities, and people not living in cities in each continent"
      Users - UC23
      UC23 - Database

      usecase UC24 as "Display the population of people, people living in cities, and people not living in cities in each region"
      Users - UC24
      UC24 - Database

      usecase UC25 as "Display the population of people, people living in cities, and people not living in cities in each country"
      Users - UC25
      UC25 - Database

      usecase UC26 as "Display the population of the world"
      Users - UC26
      UC26 - Database

      usecase UC27 as "Display the population of North America Continent"
      Users - UC27
      UC27 - Database

      usecase UC28 as "Display the population of Middle East region"
      Users - UC28
      UC28 - Database

      usecase UC29 as "Display the population of Albania country"
      Users - UC29
      UC29 - Database

      usecase UC30 as "Display the population of New South Wales district"
      Users - UC30
      UC30 - Database

      usecase UC31 as "Display the population of Sydney city"
      Users - UC31
      UC31 - Database

      usecase UC32 as "Display the percentage of world languages"
      Users - UC32
      UC32 - Database
}

@enduml
